version: "3"

services:
    web:
          build: .
          expose:
              - 80
          ports:
              - "5300:80"
          networks:
              - hangfire-network
          links:
              - db
          depends_on:
              - db          
    db:
        image: "postgres"
        expose:
            - 5432
        ports: 
            - "5432:5432"
        networks:
            - hangfire-network
        environment:
            POSTGRES_PASSWORD: "postgres"
            POSTGRES_USER: "postgres"
            POSTGRES_DB: "hangfire-db"
    app:
        image: adminer
        links:
            - db
        ports:
            - 8080:8080
        networks:
            - hangfire-network
networks: 
    hangfire-network:
        driver: bridge